### PR TITLE
Fixed Incompatible Filepath Logic

### LINKED ISSUE #82: Filepath Logic Not Compatible with Windows
Since Windows uses backslashes instead of forward flashes, **much of the functionality based on filepaths no longer work.** The problem is centralized to the use of .split("/") on file system paths specifically, and mainly affects two places:

1. `splitUri()`, used by many other functions, will not return the expected values.
2. The depth logic in the sidebar incorrectly calculates the folder depth to always be at root. 

MacOS:
image

Windows:
image

### PR DESCRIPTION
**Pull request by chrstinalin**
Fixes #82. 

**Changes**
- Reference system's file separator rather than hard-coded forward flash when dealing with file directories.

### CODE REVIEW

File: src/controller/addonController.ts [hunk 1]
```diff
@@ -82,7 +83,7 @@ export class AddonController {
 
       const workspaceFolder =
         await this.directoryController.getRootFolderPath();
-      const compressedFilePath = `${workspaceFolder}/${guid}_${version}.xpi`;
+      const compressedFilePath = [workspaceFolder, `${guid}_${version}.xpi`].join(sep);
```
Comment (willdurand) [inline src/controller/addonController.ts:86]: Why not using `path.join`, see: https://nodejs.org/api/path.html#pathjoinpaths?

**Review by willdurand — CHANGES_REQUESTED** [review]

File: src/controller/addonController.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
 import * as extract from "extract-zip";
 import * as fs from "fs";
 import fetch from "node-fetch";
+import path = require("path");
```
Comment (willdurand) [inline src/controller/addonController.ts:4]: Try not to mix import vs. require statements. This should work:

```suggestion
import * as path from "path";
```

File: src/controller/addonController.ts [hunk 3]
```diff
@@ -12,6 +13,7 @@ import { AddonInfoResponse, AddonVersion, ErrorMessages } from "../types";
 import { AddonView } from "../views/addonView";
 import { NotificationView } from "../views/notificationView";
 
+
```
Comment (willdurand) [inline src/controller/addonController.ts:16]: You probably don't need this extra line.

File: src/controller/directoryController.ts [hunk 4]
```diff
@@ -13,7 +14,7 @@ export class DirectoryController {
     const rootFolder = assayConfig.get<string>("rootFolder");
     this.setCachedRootFolder(rootFolder);
   }
-
+
```
Comment (willdurand) [inline src/controller/directoryController.ts:17]: You probably don't need these whitespaces.

File: src/controller/directoryController.ts [hunk 5]
```diff
@@ -55,14 +56,15 @@ export class DirectoryController {
...
    */
   async splitUri(uri: vscode.Uri) {
+    const sep = path.sep;
     const fullPath = uri.fsPath;
     const rootFolder = await this.getRootFolderPath();
     const relativePath = fullPath.replace(rootFolder, "");
-    const guid = relativePath.split("/")[1];
-    const version = relativePath.split("/")[2];
+    const guid = relativePath.split(sep)[1];
+    const version = relativePath.split(sep)[2];
```
Comment (willdurand) [inline src/controller/directoryController.ts:64]: You could do:

```suggestion
    const [_, guid, version] = relativePath.split(path.sep);
```

File: src/controller/lintController.ts [hunk 6]
```diff
@@ -7,6 +8,7 @@ import constants from "../config/config";
 import { Message, MessageType, ErrorMessages } from "../types";
 import { NotificationView } from "../views/notificationView";
 
+
```
Comment (willdurand) [inline src/controller/lintController.ts:11]: not needed

File: src/controller/directoryController.ts [hunk 7]
```diff
@@ -137,7 +139,6 @@ export class DirectoryController {
     if (globInitialFolder in readOnlyFiles) {
       readOnlyFiles[globInitialFolder] = false;
     }
-
```
Comment (willdurand) [inline src/controller/directoryController.ts:140]: maybe fine to keep the blank line here?

File: src/model/sidebarTreeDataProvider.ts [hunk 8]
```diff
@@ -34,8 +36,9 @@ export class AddonTreeDataProvider
   }
 
   getChildren(element?: AddonTreeItem): Thenable<AddonTreeItem[]> {
+    const sep = path.sep;
     const itemPath = element?.uri ? element.uri.fsPath : this.rootPath;
-    const depth = itemPath.split(this.rootPath)?.at(1)?.split("/").length;
+    const depth = itemPath.split(this.rootPath)?.at(1)?.split(sep).length;
```
Comment (willdurand) [inline src/model/sidebarTreeDataProvider.ts:41]: inline `path.sep`

```suggestion
    const depth = itemPath.split(this.rootPath)?.at(1)?.split(path.sep).length;
```

**Review by willdurand — CHANGES_REQUESTED** [review]

**Review by willdurand — APPROVED** [review]
Assuming tests pass, r+
