### PR TITLE
Fixed updateTaskbar.ts Filepath Error Throwing Constantly

### LINKED ISSUE #40: updateTaskbar.ts filepath error throws constantly in the Developer Tools terminal when comments are disabled.
Every time updateTaskbar is called when the activeEditor is undefined (Caused by the extension.ts [onDidChangeActiveTextEditor](https://code.visualstudio.com/api/references/vscode-api) event.), the error on line 24 of updateTaskbar.ts is thrown.

image

### PR DESCRIPTION
**Pull request by chrstinalin**
Fixes #40.

The actual reason was because the filepath changes when the user is using the commenting API, causing it not to match the root folder.

### CODE REVIEW

File: src/commands/updateTaskbar.ts [hunk 1]
```diff
@@ -16,17 +16,19 @@ export async function updateTaskbar() {
...
 
-  const doc = activeEditor.document;
-  const filePath = doc.uri.fsPath;
-  const rootFolder = await getRootFolderPath();
-  if (!filePath.startsWith(rootFolder)) {
+  const filePath = activeEditor.document.uri;
+  const { guid, rootFolder } = await splitUri(filePath);
+
+  // in comment mode. still in the same file, just not in editor itself
+  if(guid === "mozilla.assay"){
```
Comment (dotproto) [inline src/commands/updateTaskbar.ts:23]: Spacing. (Weird, I'm surprised this wasn't auto-fixed by the linter.) 

```suggestion
  if (guid === "mozilla.assay") {
```

**Review by dotproto — APPROVED** [review]
I only saw one small formatting issue. Otherwise this PR is good to go.
