### PR TITLE
More Strictly Determine the Root Folder

### LINKED ISSUE #120: checkUri() May Incorrectly Identify Root Folder
Assay checks if the full path starts with the add-ons root folder to determine whether it's inside the root folder. This doesn't account for folders such as `/root/folder-pseudo` also starting with `/root/folder`, causing it to be incorrectly identified as the root folder and activating comments.

### PR DESCRIPTION
**Pull request by chrstinalin**
Fixes #120

**Changes**
- Changed how root folder is determined to be more strict
- Removed duplicate code relating to root folder checks, routing them all through helper functions\
- Changed `updateStatusBar()` from throwing errors to returning false (since it could do the prior constantly outside of addons folder and in regular VS Code use).

### CODE REVIEW

File: src/controller/directoryController.ts [hunk 1]
```diff
@@ -70,7 +90,8 @@ export class DirectoryController {
    */
   async inRoot(uri: vscode.Uri) {
     const { rootFolder, fullPath } = await this.splitUri(uri);
-    if (fullPath.startsWith(rootFolder)) {
+    const rel = path.relative(rootFolder, fullPath);
+    if (!rel.startsWith("..")) {
       return true;
     }
     return false;
```
Comment (willdurand) [inline src/controller/directoryController.ts:97]:
```suggestion
    return !rel.startsWith("..");
```

File: src/controller/directoryController.ts [hunk 2]
```diff
@@ -18,6 +18,26 @@ export class DirectoryController {
...
+    if (!(await this.inRoot(uri))) {
+      vscode.window.showErrorMessage(
+        "(Assay) File is not in the Addons root folder."
+      );
+      throw new Error("File is not in the root folder");
+    }
+
+    if (strict && (!guid || !version)) {
+      vscode.window.showErrorMessage(
+        "Not a valid path. Ensure you are at least as deep as the version folder."
```
Comment (willdurand) [inline src/controller/directoryController.ts:35]: Not sure what "as deep as" means.

File: src/controller/directoryController.ts [hunk 3]
```diff
@@ -18,6 +18,26 @@ export class DirectoryController {
...
   }
 
+  /**
+   * Check whether a given uri is in the root folder and prompt the user accordingly.
+   */
+  async checkUri(uri: vscode.Uri, strict?: boolean) {
+    const { guid, version } = await this.splitUri(uri);
+    if (!(await this.inRoot(uri))) {
+      vscode.window.showErrorMessage(
+        "(Assay) File is not in the Addons root folder."
```
Comment (willdurand) [inline src/controller/directoryController.ts:28]: Why prefixing with "(Assay)" here and not below?

**Review by willdurand — APPROVED** [review]
r+wc, thanks
